title:              Burak Tahtacı
email:              tahtaciburak@gmail.com
description:        Yet Another R&D Engineer
author:             Burak Tahtacı
baseurl:            "/"
url:                "https://tahtaciburak.github.io"

# Social Profiles
twitter_username:   btahtaci
github_username:    tahtaciburak
facebook_username:  buraktahtaci
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-68092431-6 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
